# Generated by Django 4.0.2 on 2022-03-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/images')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('max_participant', models.DecimalField(decimal_places=0, max_digits=3)),
                ('activity_type', models.CharField(choices=[('FCFS', 'FirstComeFirstServe'), ('C', 'Candidate')], max_length=4)),
                ('register_time_start', models.DateTimeField()),
                ('register_time_end', models.DateTimeField()),
                ('activity_time_start', models.DateTimeField()),
                ('activity_time_end', models.DateTimeField()),
            ],
        ),
    ]
